### ISSUE TITLE
Latest case study not displaying on home page

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#1000]
I added a new case study to the site.
I also added a summary of the case study to the summary page.
The case study is not displaying on the home page:
https://www.ovirt.org/#case-study

Help needed from @bproffitt @duck-rh

**Comment by duck-rh** [comment]
The builder is running fine.

I tested on my laptop and it does not show up either. So something is wrong in the content. It renders an empty div…

**Comment by JohnMarksRH** [comment]
@duck-rh @bproffitt Which page affects / controls the display of the case study on the home page:
The user stories page?
https://www.ovirt.org/community/user-stories/user-stories/
Or the main case study page?
https://www.ovirt.org/community/user-stories/RCC-case-study/

Thanks

**Comment by duck-rh** [comment]
So first, the comment in _source/index.html.haml_ to look at _case-studies.html.md_ is wrong, it does not exist.

So it is looking for the first page having _page_classes: case-studies_ header defined in it, which leads to _source/community/user-stories/user-stories.html.md_ (the only one). It then extracts the content of the last study.

Unfortunately in the previous doc there is an empty block (just an empty line):
```
<div class="case-study">

</div>
```
So I guess the problem lies here.

This is really ugly and cryptic… At least we should fix the explanations in _source/index.html.haml_.

**Comment by sandrobonazzola** [comment]
@rollandf @JohnMarksRH can we close this? I see #1008 has been merged.
