### ISSUE TITLE
Sort author's blog posts in descending publication order

### ISSUE THREAD

**Issue by mureinik** [oVirt/ovirt-site#1389]
### Description of the problem
The [blogs](https://ovirt.org/blog/) are sorted in a descending publication order (newest first), which is what you'd come to expect from a blog page.
However, if you navigate to a particular author's page (e.g., [John Marks' page](https://ovirt.org/blog/author/jmarks/)), you'll find the blogs in ascending publication order (i.e., oldest first).

Could we please align these pages to also use descending order?

### Steps to reproduce
1. Navigate to https://ovirt.org/blog/author/jmarks/

**Comment by JohnMarksRH** [comment]
@mureinik Good point.
@eldan Any idea how to implement?

**Comment by mureinik** [comment]
I'm guessing @duck-rh could help here?

**Comment by eldan** [comment]
Hi,
Promise nothing, but should be easy.
Will come Tuesday to arrange it.
Eldan

**Comment by duck-rh** [comment]
The blog is handled by an extension, and the code seem to already sort in descending date order. I see no setting which could alter that. So I'm not sure why it is not sufficient; maybe due to the author filtering.

We could try to add a `sort_by(&:date)` in `source/layouts/_blog_posts.haml` in between `select()` and `take()`. I don't have time to experiment now , sorry.

**Comment by sandrobonazzola** [comment]
@eldan , @duck-rh any update?
