### ISSUE TITLE
Some internal links are broken

### ISSUE THREAD

**Issue by david-caro** [oVirt/ovirt-site#14]
http://beta-ovirtweb.rhcloud.com/community/
there's a link to http://beta-ovirtweb.rhcloud.com/community/develop/infra/infrastructure that should be http://beta-ovirtweb.rhcloud.com/develop/infra/infrastructure/

**Comment by thatdocslady** [comment]
@garrett it looks like @mscherer tried to fix the broken link but he used a relative path to /develop/infra... and the link ended up generating _under_ the /community/ parent instead of <base-domain>/develop/etc...

Is this a Middleman thing? Can/should we enforce relative paths to "start" from the base URL instead of under the immediate parent directory?

**Comment by garrett** [comment]
It should work if you link to "/develop/infra/infrastructure/", using normal linking, or "Infrastructure", with the wiki workaround in place. If it doesn't work with either of those two, then it's possibly a bug in my linking override code.

**Comment by garrett** [comment]
FWIW: The example appears to be fixed. Redirects are now handled in Middleman instead of relying on Apache, so all other link redirects should work properly too. If you find other redirect links that are a problem, please open up another issue, or reopen this one. Thanks!
