### ISSUE TITLE
some links are prepended with '<' when rendered

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#1503]
### Description of the problem
You can see the issue in https://www.ovirt.org/release/4.1.9/ ; the instructions for installing the release rpm are displayed as: 
`# yum install <http://resources.ovirt.org/pub/yum-repo/ovirt-release41.rpm`

but the markdown code doesn't have the '<' character.

**Comment by duck-rh** [comment]
The following block has a similar problem. I'm looking into it.

As for the formatting, the backquotes are for inline code AFAIK, so why not use a blockcode as below?

**Comment by duck-rh** [comment]
In fact there's many other places like (https://www.ovirt.org/develop/release-management/releases/3.4.1/) where this bug is present.

The problem is again `markdown_to_html` which previously caused similar problems. It does magic to create a link when the URL is set without markdown formatting. Not sure what was the initial intent but we don't need this.

I would then suggest to remove this magic and fix the few links which lack formatting. I'm attaching a diff of the build result (containing both fixed and broken links). A few are missing formatting in the site itself (source/release/4.2.0/index.html.md) but some also lies in the events.

[ovirt_1503_build.txt](https://github.com/oVirt/ovirt-site/files/1771184/ovirt_1503_build.txt)

**Comment by duck-rh** [comment]
@sandrobonazzola any thoughts on this? Would you (all) be ok to fix the few broken things if I removed the hack in `markdown_to_html`?

**Comment by sandrobonazzola** [comment]
@duck-rh I'm ok with the proposed solution.
