### ISSUE TITLE
Wrong linked category in the 'becoming an infra team member' page

### ISSUE THREAD

**Issue by david-caro** [oVirt/ovirt-site#20]
the page: http://beta-ovirtweb.rhcloud.com/develop/infra/becoming-an-infrastructure-team-member/

**Comment by garrett** [comment]
Categories are no longer used, as this isn't MediaWiki.

Simple fix is to remove the link at the bottom of the page. Categories are supported in the metadata, and the conversion should have caught the links and converted them to metadata for the most part.

During conversion, category information was initially used for a starter filesystem layout, which was then revised (as many pages lacked categories and other matchers). Category pages, in general, became index pages within the directories they represent, unless another index page existed. Some index pages since then were deleted and now auto-generated index pages simply show files contained within the directory.

**Comment by thatdocslady** [comment]
looks like @garrett 's patch fixed the issue, closing
