### ISSUE TITLE
Wrongly rendered quotes (seen in in a cople pages iirc)

### ISSUE THREAD

**Issue by david-caro** [oVirt/ovirt-site#21]
one of them http://beta-ovirtweb.rhcloud.com/develop/infra/infra-bash-style-guide/

**Comment by garrett** [comment]
Please add any other pages where you've seen this issue.

Using a quick grep for `&amp;`, `&gt;`, or `&quot;`, I've found the following pages match:

* community/get-involved/wiki-rules-and-etiquette.html.md
* develop/developer-guide/vdsm/hook/vmfex.html.md
* develop/dev-process/working-with-gerrit.html.md
* develop/infra/phoenix-lab-hosts.html.md
* develop/infra/phoenix-lab-ssh-spice-tunnel.html.md
* develop/infra/phoenix-lab-storage-hosts.html.md
* develop/infra/proxy.html.md
* develop/release-management/features/storage/cinder-integration.html.md
* develop/release-management/features/ux/detailedhostpmmultipleagents.html.md
* documentation/admin-guide/administration-guide.html.md

...I suppose those can be added to the pending pull request. (The branch name would make less sense, but whatever.)

This is basically because the tools used for the conversion to Markdown aren't perfect, and sometimes have issues with code blocks.

Thankfully the list above isn't so bad. I'm guessing offending pages will most likely use `&`, `>`, and/or `"`. There may be additional pages that use _other_ escaping, but I highly doubt they wouldn't use one of these I quickly searched for too.
