### ISSUE TITLE
http://www.ovirt.org/stats/ from bitergia is not working anymore

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#232]

**Comment by garrett** [comment]
The stats are at:
http://projects.bitergia.com/redhat-ovirt-dashboard/browser/

...previously, before the wiki conversion to middleman, they were sync'd in and server via some Apache rule. Since the conversion, the syncing has been dropped. @mscherer or @duck-rh would need to do something to restore the sync and webserver graft.

(Meanwhile, the above link still works.)

**Comment by duck-rh** [comment]
Quack,

On 06/21/2016 12:40 AM, Garrett LeSage wrote:
> The stats are at:
> http://projects.bitergia.com/redhat-ovirt-dashboard/browser/
> 
> ...previously, before the wiki conversion to middleman, they were sync'd
> in and server via some Apache rule. Since the conversion, the syncing
> has been dropped. @mscherer <https://github.com/mscherer> or @duck-rh
> <https://github.com/duck-rh> would need to do something to restore the
> sync and webserver graft.

There is nothing on the oVirt builder but I figured out it would be the
same sort of things we have for the community dashboard, limited to this
specific project.

I can work on this part, as it is Ruby code. It should be possible to
adapt a bit to format for a single or multiple sources using the same
script and page. Would be nice to share the code between all sites.

\_o<

**Comment by mscherer** [comment]
I am not convinced that we need to sync, what about just redirect people to the bitergia dashboard ?

**Comment by garrett** [comment]
Yeah, I'm fine with a redirect. It's easiest for all involved, and doesn't have any duplication of locations.

**Comment by duck-rh** [comment]
Quack,

On 06/22/2016 01:42 AM, Garrett LeSage wrote:
> Yeah, I'm fine with a redirect. It's easiest for all involved, and
> doesn't have any duplication of locations.

Well, too late, I already worked on it.

So I've made a few simple changes to separate the config from the code
and adapt the presentation. I think we should consider merging it anyway.

I'm not allowed to push to community-middleman (where I made the patch
to ensure it still work). could one of you allow me to push a branch to
made a PR?

Then, just borrowing the files for oVirt, removing the parts of the
config for other projects, and ensuring to have /stats instead of
/dashboard should not be difficult.

\_o<

**Comment by duck-rh** [comment]
Quack,

On 06/22/2016 02:11 AM, Marc Dequènes (Duck) wrote:

> I'm not allowed to push to community-middleman (where I made the patch
> to ensure it still work). could one of you allow me to push a branch to
> made a PR?

This is still relevant, so as to have a unique version of the code.

> Then, just borrowing the files for oVirt, removing the parts of the
> config for other projects, and ensuring to have /stats instead of
> /dashboard should not be difficult.

done in PR #312

\_o<

**Comment by sandrobonazzola** [comment]
Despite PR #312 http://www.ovirt.org/stats/ is still 404 not found

**Comment by duck-rh** [comment]
That's a different issue: before the data were not updated and the stats file not created, now the stats page is created without extension (build/stats). The content of the file seems ok, just the naming is wrong.

we have this config:
  proxy 'stats', '/dashboard.html'

the 'build/dashboard/index.html' file is well created.

the other proxy commands define the extension is wanted, to I guess the bug is in the proxy definition. What is strange is the change of behavior. Will issue a fix.
