### ISSUE TITLE
[Docs] Menu delimiters in oVirt documentation are corrupted

### ISSUE THREAD

**Issue by stoobie** [oVirt/ovirt-site#2413]
### Description of the problem
The delimiters in descriptions of cascading menu items do not appear correctly. See attached screenshot of https://www.ovirt.org/documentation/administration_guide/#Removing_a_host for example.

#### Type of problem?
Documentation formatting issue.

Browser: Firefox 78.4.0esr (64-bit) for Linux

![corrupted_delimiters](https://user-images.githubusercontent.com/39279277/103417902-3ff28200-4b95-11eb-85c5-a2f3fc4fa512.png)

**Comment by sandrobonazzola** [comment]
Compute -> hosts is translated to html:

```html
<span class="menuseq">
<b class="menu">Compute</b>&nbsp;<i class="fa fa-angle-right caret"></i> <b class="menuitem">Hosts</b>
</span>
```

same code is rendered in RHV guide as:
```html
<span class="guimenu">Compute</span> → <span class="guimenuitem">Hosts</span>
```

The common asciidoc code is:
```
. Click menu:Compute[Hosts] and select the host.
```

Need to find out how this is being translated.

**Comment by sandrobonazzola** [comment]
@duck-rh any suggestion?

**Comment by duck-rh** [comment]
@sandrobonazzola I'm having a look at it. It's related to the Awesome font and icons rendering. I'm not familiar with this, so I'm investigating. Bumping `jekyll-font-awesome-sass` to the latest version does not improve the situation.

**Comment by bencurio** [comment]
The source of the problem is an extra class.

![image](https://user-images.githubusercontent.com/7604637/116536237-f3ba1300-a8e4-11eb-825f-63ac59dd059e.png)

If I remove it, it will display correctly.

![image](https://user-images.githubusercontent.com/7604637/116536364-19dfb300-a8e5-11eb-8d0d-85ad5e9aa17e.png)

**Comment by sandrobonazzola** [comment]
seems like the issue is here: https://github.com/asciidoctor/asciidoctor/blob/9137bf05ca5458bc62ed33a11cf85265b8c85ce8/lib/asciidoctor/converter/html5.rb#L1232 on RHV docs we use the font and in ovirt we are using the icon.

**Comment by bencurio** [comment]
Hmm... The problem is actually caused by the bootstrap CSS, which can be found here: 

https://github.com/twbs/bootstrap-sass/blob/v3.4.1/assets/stylesheets/bootstrap/_dropdowns.scss#L6-L17

It seems that the best solution would be to overwrite the CSS locally.

I would suggest that you use the first CSS code part of my last comment, which has the least possible impact on other page elements.

Should I open a separate pull request for this?
**Preview:**

---

![image](https://user-images.githubusercontent.com/7604637/116721187-54c51200-a9dd-11eb-9500-72534f74fc56.png)

**Comment by sandrobonazzola** [comment]
Ok, let's go with your proposal. Can you send a PR for it?

**Comment by duck-rh** [comment]
thanks a lot @bencurio I was not able to spot the problem.

@sandrobonazzola The fix as is is fine but I'm wondering why do we use icons instead of the font, since nowadays fonts are more complete and many are available as webfonts. Maybe we should consider trying using the same as RHV, that would also remove a diverging setting.

**Comment by stoobie** [comment]
> thanks a lot @bencurio I was not able to spot the problem.
> 
> @sandrobonazzola The fix as is is fine but I'm wondering why do we use icons instead of the font, since nowadays fonts are more complete and many are available as webfonts. Maybe we should consider trying using the same as RHV, that would also remove a diverging setting.

+1
