### ISSUE TITLE
can't access specific Developer guide pages from Developers tab

### ISSUE THREAD

**Issue by saifabusaleh** [oVirt/ovirt-site#2530]
#### Type of problem?
Documentation issue

I recently came across this guide by someone that linked me to it:  https://www.ovirt.org/develop/developer-guide/engine/building/ide.html

However, the guide is not accessible from the website

For example, if a normal user want to find the above page after entering https://www.ovirt.org website manually, how he can find it?

I found that there is few pages from the developer-guide linked from here: https://www.ovirt.org/develop/devdocs.html (which is accessible from Developers tab ->  developers documentation), but what about the other ones?

And also, why is https://www.ovirt.org/develop/devdocs.html showing as outdated?

Thanks,
Saif

**Comment by sandrobonazzola** [comment]
I guess there are several other pages not linked within the website.
We have automation for detecting broken links but not for detecting orphan pages.
The specific page is indexed from https://ovirt.org/develop/developer-guide/engine/building/index.html but not linked in any other page as far as I can tell.

The whole developer section is largely unmaintained and that's the reason it's marked as outdated.
We should review the whole content there and drop the outdated warning on those that are not really outdated.

**Comment by saifabusaleh** [comment]
I agree,
I think all the not-outdated pages should be simply accessed from single place (for example: https://www.ovirt.org/develop/devdocs.html)
Current structure is really confusing and there is no single place that contains all the developer docs information

Let me know how I can contribute/help with this :)

**Comment by sandrobonazzola** [comment]
@sanjacodes @janosdebugs you may have thoughts on this as well.
We should give some organized structure to the developer section to ease new developers onboarding experience.
I'm open to suggestions :-)

**Comment by janosdebugs** [comment]
@sandrobonazzola we just discussed this and we'd be happy to take on reorganizing the website. It isn't too much work. However, we are going to need help with writing the part how oVirt is developed as we are not oVirt developers ourselves and don't have a dev env for it.

**Comment by saifabusaleh** [comment]
Suggestion:

What about having all the developer docs with something similar to this structure: https://ovirt-infra-docs.readthedocs.io/en/latest/
also same structure is used for ost: https://ovirt-system-tests.readthedocs.io/en/latest/general/installation/index.html

It is very simple, all the guides is accessible/searchable from one place

I know that moving all the dev docs into other website would be a lot of work, other option is to add similar UI to the ovirt-site.
do we have support for design like this in the ovirt-site project?

**Comment by janosdebugs** [comment]
Thank you for your suggestion @saifabusaleh. We had a meeting with @sandrobonazzola and we have decided that we are taking on the challenge of reorganizing the content with @sanjacodes.

The main challenge will be organizing the content in a meaningful fashion as there are loads of orphaned pages, files that were never finished, etc. so we need to go through and weed out the useless parts.

As for the visuals, the pages you linked were built with mkdocs and that structure is very hard to replicate with Jekyll (the current engine). Introducing one more system next to Jekyll and Wordpress does noone a service, which is why we are attempting to rebuild the entire site using [Hugo](https://gohugo.io/). That one covers both use cases and we have considerable experience developing for it, as well as a lot of the stuff we need already done.

If you want to help out poke me on chat, that's more efficient than trying to sort things out via issues. :)

**Comment by duck-rh** [comment]
As far as I know nothing was decided about a migration to Hugo, or my team was not included in the discussion. There's a plethora of website generator and each and everyone comes with their own personal preferences, so unless we have good reason to support yet one more engine, or someone else takes over the whole maintenance and support from OSPO's shoulders then no such thing is going to happen. Not that I'm closed to discussion but when we first talked with @janosdebugs he was just barely joining the effort and already wanted to change everything but it lacked any good reason past personal preferences, so at the moment I'm not convinced this is really going to help oVirt.

**Comment by sandrobonazzola** [comment]
Another related thread @janosdebugs https://lists.ovirt.org/archives/list/users@ovirt.org/thread/VXXYO4KAINCVW4ENQOURATYY3OW5HRXQ/
