### ISSUE TITLE
 bundle exec ruby htmlproofer_test.rb not running in GitHub actions

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2826]
#### Type of problem?
automation bug

`Preview build` GitHub actions is supposed to run ` bundle exec ruby htmlproofer_test.rb` but the command is not really running or not running on the generated content as it doesn't report errors which are there when running manually on local instance (see #2822 )

**Comment by duck-rh** [comment]
I don't get it. It was tested, many problems were fixed at the time before it was green, so what changed?

**Comment by apinnick** [comment]
It was tested before downstream docs were added to the upstream repo. This is a false positive -- the downstream attributes do not appear in the upstream section of the attributes file, so it cannot resolve them. I could create a PR with the attributes added. Since the errors only affect downstream docs (Python guide, Planning guide, deprecated Gluster guide), it should not affect the upstream docs in a negative way.

I will create a PR to test this..

**Comment by duck-rh** [comment]
@apinnick I guess you replied on the wrong ticket. Whatever we think is right for #2822 the GH workflow should fail if htmlproofer reports anything.
