### ISSUE TITLE
Links 'Editing this wiki' and 'Organising pages in the wiki' don't work

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-site#422]
### Description of the problem

Links at http://www.ovirt.org/documentation/, section Community documentation point at 'help:Editing' resp. 'help:Wiki_structure'.

**Comment by garrett** [comment]
Yep. This is a known side effect from data being ported from the wiki, and it is still waiting for people to step up and fix the documentation.

I could have removed them all, but it could possibly break the text — and some pages, like this one, need to be re-edited to make sense, rather than just deleting (old, broken) links.

The proper way to edit a page from the website is to scroll down and click on "Edit this page on GitHub" on any page. It will then open up the page editing interface on GitHub.

"Help:" is not a proper link. In this instance, those links need to point to pages that talk about how to properly do this in the "new" non-wiki way.

**Comment by garrett** [comment]
Here are the places where "help:" links still exist:

```
source/community/about/community-guidelines.html.md:
68:    -   For more details on page naming, refer to <Help:Wiki_structure>.

source/documentation/index.html.haml:
101:      - [Editing this wiki](Help:Editing)
102:      - [Organising pages in the wiki](Help:Wiki_structure)
```

Thankfully, at this time, it's not really a lot. It's mainly the one documentation page that's left.

**Comment by gregsheremeta** [comment]
closing old issues
