### ISSUE TITLE
https://ovirt.org doesn't work

### ISSUE THREAD

**Issue by happylynx** [oVirt/ovirt-site#813]
### Description of the problem
https://ovirt.org site has non-trusted certificate and it doesn't redirect to https://www.ovirt.org. It returns 400 Bad request.
Note: http://ovirt.org is redirected properly.

### Steps to reproduce

1. Open https://ovirt.org in browser

2.

3.

### Help needed from (use @mention to request assistance)
@bproffitt

**Comment by bproffitt** [comment]
@mscherer @duck-rh I remember there being a reason for this. Can you elaborate?

**Comment by mscherer** [comment]
So, before, it was because we were using openshift. ovirt.org is the apex domain, and can't be pointing to a CNAME (some RFC forbid it), and openshift requires it (to handle containers migration in a seamless way). So we have to get something to redirect somewhere, and until recently, we were using RHIT for that service (as we didn't had anything to do the hosting ourself, no VMs, no servers), but the appliance didn't seems to support TLS/SNI or something like this, so we couldn't have proper SSL certs there. Or maybe they just didn't provide that service as in retrospect, there shouldn't have been any limitation on the technical side.

Now, I just found out that ovirt.org point to mail.phx.ovirt.org, which is a server managed by ovirt folks. So, a certificate could be added there. I am however unable to connect to that server, so I will let @duck-rh handle that. (or if anyone drop my ssh key, as I think Duck is gonna be out, I can take a look next week)

**Comment by duck-rh** [comment]
Quack,

There was a redirection for HTTP, not HTTPS. I added it so it seems to be fine. Could someone else test it and report please?

**Comment by rollandf** [comment]
Works for me 👍

**Comment by duck-rh** [comment]
thanks, closing then.
