### ISSUE TITLE
Mixed non-ssl resources on the ssl page

### ISSUE THREAD

**Issue by david-caro** [oVirt/ovirt-site#87]
Hi,
So after enabling the correct cert, when loading the ssl-enabled page firefox complains about a couple resources not being fetched from secure connections, the resources are:

   http://www.redhat.com/j/elqNow/elqCfg.js
   http://www.redhat.com/j/elqNow/elqImg.js

The https counterparts already work, so probably it's just a matter of changing a hardcoded url somewhere

**Comment by thatdocslady** [comment]
@garrett is this something you can help with?

**Comment by garrett** [comment]
Nope, unless those are available at https too. The site should technically refer to those links with `//` instead of `http://` so they use the same resource as the calling site (http if http, https if https).

A quick look seems to confirm that https works for those links... so they should be referred to as `//www.redhat.com/j/elqNow/elqCfg.js` and `//www.redhat.com/j/elqNow/elqImg.js`.
