### ISSUE TITLE
'source/images/wiki' folder was updated 8 monthes before the site migration date

### ISSUE THREAD

**Issue by yevgenyz** [oVirt/ovirt-site#97]
Example of the problem: [IPv6 support feature page](http://old.ovirt.org/Features/IPv6_support) referrers to [the image file](http://old.ovirt.org/File:Edit_network_ipv6.jpg) that is present in the legacy site and is missing from the new one.

**Comment by thatdocslady** [comment]
@yevgenyz as a best practice, please link to the new page as well as the old page. Otherwise, I just merged a PR with all of the missing images that weren't copied from the old wiki, so please check whether this is fixed and let me know. If the image is still missing and you are the owner of this feature, please add the image again to the new page.

**Comment by dankenigsberg** [comment]
Mikey, your pull request https://github.com/oVirt/ovirt-site/commit/d337b685bd0b5ea640448d107c48cdb05fb06afd does not include the image that Yevgeny mentioned http://old.ovirt.org/File:Edit_network_ipv6.jpg .

May I ask how did you create the list of images that need update? Apparently, at least one image is missing from it.

**Comment by gpadgett** [comment]
Adding to this, the [flow diagram](http://www.ovirt.org/images/wiki/Image_Upload-HTTP_Sequence_Diagram.png?1454370862) on the [Image Upload](http://www.ovirt.org/develop/release-management/features/image-upload/) page is outdated by a few versions.

I'm happy to submit a pull request with the updated diagram, but am concerned that not all pages would get the same attention.

**Comment by sandrobonazzola** [comment]
Closing this issue. The wiki is gone and if we still have images missing, we need to add them from scratch.
